# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 684e4521e11dbf18eb59a275a38c58d0fd6c1d6c99e8adfcdda49f530244c25e7a77238dce2502e6e3c4a7a401f5d4547b183e3500c3c26c4fa5cc4c444b62f0

test:
  secret_key_base: 33337746780cff8162a437b61a3bb068b4163561db33699ed64c3b07e5cbcd4ba3fbf6d93d67a0560e59342458629db7198cd060f0025bb73349d7e2ae51ddf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
